import Head from "next/head";
import LottieInfinite from "../components/animations/lottie.infinite";
import Conclusion from "../components/home/conclusion";
import Content from "../components/home/content";
import Hero from "../components/home/hero";
import Layout from "../components/layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Hero></Hero>
        <Content></Content>
        <Conclusion></Conclusion>
      </Layout>
    </div>
  );
}
