import Head from "next/head";
import LottieInfinite from "../components/animations/lottie.infinite";
import Layout from "../components/layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <hero />
      </Layout>
    </div>
  );
}
